"""initial migration

Revision ID: efd31f645589
Revises:
Create Date: 2026-08-08 20:36:39.703557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "efd31f645589"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flightsearchhistory",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("destination", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("departure_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("return_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column("children", sa.Integer(), nullable=False),
        sa.Column("infants", sa.Integer(), nullable=False),
        sa.Column("cabin_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("searched_at", sa.DateTime(), nullable=False),
        sa.Column("direct_only", sa.Boolean(), nullable=False),
        sa.Column("sort_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userindb",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userindb_email"), "userindb", ["email"], unique=True)
    op.create_table(
        "flightorder",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("flight_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("airline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("destination", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("departure_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("booking_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userindb.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flightorder_user_id"), "flightorder", ["user_id"], unique=False
    )
    op.create_table(
        "booking",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("flight_order_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_order_id"],
            ["flightorder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userindb.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flight_order_id"),
    )
    op.create_index(op.f("ix_booking_user_id"), "booking", ["user_id"], unique=False)
    op.create_table(
        "traveler",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("passport_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("passport_expiry", sa.Date(), nullable=True),
        sa.Column(
            "passport_country", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["flightorder.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("traveler")
    op.drop_index(op.f("ix_booking_user_id"), table_name="booking")
    op.drop_table("booking")
    op.drop_index(op.f("ix_flightorder_user_id"), table_name="flightorder")
    op.drop_table("flightorder")
    op.drop_index(op.f("ix_userindb_email"), table_name="userindb")
    op.drop_table("userindb")
    op.drop_table("flightsearchhistory")
    # ### end Alembic commands ###
